### ISSUE TITLE
python_match.vim installation failed

### ISSUE THREAD

**Issue by babygoat** [moskytw/mosky.vim#2]
Hello,
Thanks in advance for sharing the vimrc and some useful plugins for a python new comer. An issue occurred during the installation, which I thought could be documented for others willing to try or could be considered an improvement in the future.

*   init.vim#L38
      Installation would fail if vim-plug approach is applied. As the implicit fallback was deprecated ( 
junegunn/vim-plug@f7e6a868 ), I suggested the repo prefix should be prepended ( Plug 'vim-scripts/python_match.vim' ).

**Comment by moskytw** [comment]
Thanks! Should be fixed already. https://github.com/moskytw/mosky.vim/blob/master/init.vim#L38
